import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for the CreditPhone QA application.
///
/// The values included here are based on the existing Android configuration in
/// the repository. Web values are placeholders and should be replaced with the
/// real configuration generated by `flutterfire configure` once the Firebase
/// CLI is available.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'Run flutterfire configure to generate the Firebase options.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
          'Run flutterfire configure to generate the Firebase options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
          'Run flutterfire configure to generate the Firebase options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Run flutterfire configure to generate the Firebase options.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Fuchsia. '
          'Run flutterfire configure to generate the Firebase options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSl6tHzf6x-WQAC4ecuuquoUGtwFfvUn8',
    appId: '1:641037176066:web:placeholder',
    messagingSenderId: '641037176066',
    projectId: 'book-3d7c1',
    authDomain: 'book-3d7c1.firebaseapp.com',
    storageBucket: 'book-3d7c1.appspot.com',
    measurementId: 'G-PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSl6tHzf6x-WQAC4ecuuquoUGtwFfvUn8',
    appId: '1:641037176066:android:ceb3c46ae5f4436cc2061b',
    messagingSenderId: '641037176066',
    projectId: 'book-3d7c1',
    storageBucket: 'book-3d7c1.appspot.com',
  );
}
